### PR TITLE
Change the version for sdkDocUrl according to current zenml version.

### PR DESCRIPTION
**Pull request by talhainvenxion**
https://zenml.atlassian.net/browse/DAS-378

### CODE REVIEW

**Comment by talhainvenxion** [comment]
> Is this logic running always, or do we check if the version is the correct one?
> 
> Doing this thing in the frontend is rather dirty, so I would only do it if necessary.

@Cahllagerfeld  How can we check if the version is correct or not? Secondly, I don't think we need to check it because we are modifying SdkDocsUrl with the version we getting from "https://appserver.zenml.io/api/v1/version".

**Review by Cahllagerfeld — COMMENTED** [review]
@AlexejPenner Short semantical question. By fetching the version from the `/version` endpoint, we potentially fetch a version that is not the newest release (outdated server version). Is it correct, that we tie the displayed version to the server-version, or do we need the latest version from all zenml releases here?

**Review by Cahllagerfeld — COMMENTED** [review]
I just spoke to @AlexejPenner and we came to the following conclusion: We shouldn't tie the sdc-Docs URL to the Server-Version like we do here. Do you think there might be a solution where we do this only, if the given URL from the DB leads to a 404? 🤔

**Comment by talhainvenxion** [comment]
> I just spoke to @AlexejPenner and we came to the following conclusion: We shouldn't tie the sdc-Docs URL to the Server-Version like we do here. Do you think there might be a solution where we do this only, if the given URL from the DB leads to a 404? 🤔

I'll look into this and try to come up with a solution.

**Comment by talhainvenxion** [comment]
@Cahllagerfeld I have used this approach to find a solution to our problem.

**Review by Cahllagerfeld — COMMENTED** [review]
I'm not sure if it's related to this change but if you go to the [deployment-preview](https://deploy-preview-448--zenml-ui-dev.netlify.app/workspaces/default/registerComponents/artifact_store) and then select `My-Artifact-Store`, the application breaks. I also checked it on UAT, and there is also nothing displayed, but at least the app doesnt break

**Comment by talhainvenxion** [comment]
> I'm not sure if it's related to this change but if you go to the [deployment-preview](https://deploy-preview-448--zenml-ui-dev.netlify.app/workspaces/default/registerComponents/artifact_store) and then select `My-Artifact-Store`, the application breaks. I also checked it on UAT, and there is also nothing displayed, but at least the app doesnt break

@Cahllagerfeld It is because we are getting sdkDocsUrl 'null' from back-end but I fixed this issue on front-end. It won't break again.

**Pull request merged**
