### PR TITLE
Qa fixes connectors

### PR DESCRIPTION
**Pull request by talhainvenxion**
We have resolved the bugs. Please review them.

https://zenml.atlassian.net/browse/DAS-384
https://zenml.atlassian.net/browse/DAS-388
https://zenml.atlassian.net/browse/DAS-391
https://zenml.atlassian.net/browse/DAS-383
https://zenml.atlassian.net/browse/DAS-387
https://zenml.atlassian.net/browse/DAS-389
https://zenml.atlassian.net/browse/DAS-394
https://zenml.atlassian.net/browse/DAS-393
https://zenml.atlassian.net/browse/DAS-399
https://zenml.atlassian.net/browse/DAS-392

### CODE REVIEW

**Comment by stefannica** [comment]
Wonderful work ! I re-tested all linked Jira issues and I can conclude that this PR fixes all of then with the exception of the following 2:

* https://zenml.atlassian.net/browse/DAS-384 (Component List tab in Connector Details shows incorrect resource type and resource ID): resource type still doesn't show for some components (details in the ticket)
* https://zenml.atlassian.net/browse/DAS-392 (Service Connector verification not triggered on optional fields): the solution to these two issues is not ideal from a UX perspective. Yes, pushing the create button will now trigger the "verification" if an optional field is updated or if only optional fields are present, but the behavior is not consistent between mandatory and optional fields. To ensure a smooth user experience, the "verification" should also be triggered when a optional field is exited and (only) if its value has changed since it was entered, same as we do for mandatory fields.

**Comment by talhainvenxion** [comment]
> * exited

@stefannica These issues have been fixed kindly verify.

**Comment by talhainvenxion** [comment]
> Wonderful work ! I re-tested all linked Jira issues and I can conclude that this PR fixes all of then with the exception of the following 2:
> 
> * https://zenml.atlassian.net/browse/DAS-384 (Component List tab in Connector Details shows incorrect resource type and resource ID): resource type still doesn't show for some components (details in the ticket)
> * https://zenml.atlassian.net/browse/DAS-392 (Service Connector verification not triggered on optional fields): the solution to these two issues is not ideal from a UX perspective. Yes, pushing the create button will now trigger the "verification" if an optional field is updated or if only optional fields are present, but the behavior is not consistent between mandatory and optional fields. To ensure a smooth user experience, the "verification" should also be triggered when a optional field is exited and (only) if its value has changed since it was entered, same as we do for mandatory fields.

@stefannica These issues have been fixed kindly verify.

**Comment by stefannica** [comment]
> > Wonderful work ! I re-tested all linked Jira issues and I can conclude that this PR fixes all of then with the exception of the following 2:
> > 
> > * https://zenml.atlassian.net/browse/DAS-384 (Component List tab in Connector Details shows incorrect resource type and resource ID): resource type still doesn't show for some components (details in the ticket)

This one has been fixed, thank you !

> > * https://zenml.atlassian.net/browse/DAS-392 (Service Connector verification not triggered on optional fields): the solution to these two issues is not ideal from a UX perspective. Yes, pushing the create button will now trigger the "verification" if an optional field is updated or if only optional fields are present, but the behavior is not consistent between mandatory and optional fields. To ensure a smooth user experience, the "verification" should also be triggered when a optional field is exited and (only) if its value has changed since it was entered, same as we do for mandatory fields.

This has only been half-fixed: "verification" is indeed triggered now when exiting an optional field, but not if the user *deletes* a value from an optional field. Good to merge to release the other fixes, but the DAS-384 Jira ticket should remain open.

> 
> @stefannica These issues have been fixed kindly verify.

**Review by Cahllagerfeld — COMMENTED** [review]
As Stefan said, I'd say we merge this PR, to get the fixes in the current release, and tackle open things in the next spring 👍
Ideally we create more smaller PRs, which is easier to review 👍

**Pull request merged**
