### PR TITLE
fixed issue related zoom in controls

### PR DESCRIPTION
**Pull request by talhainvenxion**
https://github.com/zenml-io/zenml-dashboard/issues/356

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
grafik

I feel like we should tweak the UI. In looks kinda buggy or cutoff at the moment 🤔

**Comment by talhainvenxion** [comment]
> I feel like we should tweak the UI. In looks kinda buggy or cutoff at the moment

Could you please suggest ways we can improve it?

**Comment by Cahllagerfeld** [comment]
grafik
When hovering the buttons, there's a white background on the icons. I think it's not related to this issue though. If we can get this as a quick fix done, we can release the feature, otherwise let's merge it and open a followup

**Comment by talhainvenxion** [comment]
> grafik When hovering the buttons, there's a white background on the icons. I think it's not related to this issue though. If we can get this as a quick fix done, we can release the feature, otherwise let's merge it and open a followup

@Cahllagerfeld  this issue has been fixed kindly check.

**Pull request merged**
