### PR TITLE
Minor bugfixes

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
- [x] in case its a local deployment (`local` or `docker`), dont show `zenml connect`
- [x] allow items to be unchecked
- [x] allow icon to be clickable to collapse the onboarding item
- [x] add init command
- [x] added tests for new helper functions

### CODE REVIEW

**Review by avishniakov — APPROVED** [review]
Not fully understand this syntax, but looks logical to the PR description 👍🏼

**Comment by htahir1** [comment]
@Cahllagerfeld are you sure about the “docker” case? And can you add screenshots

**Comment by Cahllagerfeld** [comment]
@stefannica told me to check localServer its deploymenttype `local` and `docker`

**Comment by htahir1** [comment]
@stefannica xan we check the database type instead? Whether it’s MySQL or not

**Comment by htahir1** [comment]
Whether it’s not SQLite maybe that’s better

**Comment by Cahllagerfeld** [comment]
grafik
grafik
grafik

Not so many changes to see in the screenshots

**Review by htahir1 — APPROVED** [review]

**Pull request merged**
