### PR TITLE
get latest release version as UI version

### PR DESCRIPTION
**Pull request by talhainvenxion**

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
Without setting it to the environment would, it make sense to update the version in the package.json accordingly and import it from there? What do you think?

**Comment by talhainvenxion** [comment]
> Without setting it to the environment would, it make sense to update the version in the package.json accordingly and import it from there? What do you think?

@Cahllagerfeld I think we can't directly import the version from package.json either we can set it to an env file that's what we are doing or the other way is to make a separate file to get version from git and export it from there.

**Comment by Cahllagerfeld** [comment]
Maybe I'm missing something, but why can't we set it to the environment while building? 😅

**Comment by talhainvenxion** [comment]
@Cahllagerfeld I found this solution for UI version. kindly look into it.

**Comment by Cahllagerfeld** [comment]
I'm closing this in favor of #458

**Pull request closed without merging**
