### PR TITLE
Ahsan service connector

### PR DESCRIPTION
**Pull request by AhsanInvexion**

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
grafik

There seems to be an issue with the sidebar.
Also when clicking the button `Register Connector` it displays a blank page.

Do we need to setup anything else before being able to test it?

**Comment by AhsanInvexion** [comment]
- the sideBar issue will be fixed on the next PR
- we are working on the "register connector" screen, that's why it shows the blank page
- as for now we are using the docker image. the connector APIs have not been deployed on app-server

**Comment by talhainvenxion** [comment]
> * the sideBar issue will be fixed on the next PR
> * we are working on the "register connector" screen, that's why it shows the blank page
> * as for now we are using the docker image. the connector APIs have not been deployed on app-server

**Review by talhainvenxion — COMMENTED** [review]
Ahsan, can you please fix the sidebar issue in this PR?

**Pull request merged**
